package tools

import "encoding/json"

func init() {
	registry = append(registry, []entry{
		{Definition{"make_checklist", "Create a Markdown checklist from a title and 1 to 100 supplied task strings. This only exports text; it does not create reminders or perform tasks.", "planning", object(map[string]any{"title": str(120), "items": array(str(500), 1, 100)}, "title", "items"), json.RawMessage(`{"title":"Release prep","items":["Test the app","Review screenshots","Submit the update"]}`)}, makeChecklist},
		{Definition{"make_table", "Create CSV and Markdown tables from 1 to 16 header strings and 0 to 100 rows of string cells. Every row must match the header count. Quoting and Markdown escaping are server-owned. No formulas or calculations.", "writing", object(map[string]any{"headers": array(str(120), 1, 16), "rows": array(array(str(1000), 1, 16), 0, 100)}, "headers", "rows"), json.RawMessage(`{"headers":["Subject","Hours"],"rows":[["C","4"],["Python","7"]]}`)}, makeTable},
		{Definition{"make_identicon", "Create a deterministic 5x5 mirrored SVG avatar from a seed string using SHA-256. Same seed gives the same icon. No photos, scripts, external assets, or generative AI. Return SVG text.", "visuals", object(map[string]any{"seed": str(1000)}, "seed"), json.RawMessage(`{"seed":"Edsger"}`)}, makeIdenticon},
		{Definition{"color_contrast", "Compute WCAG sRGB contrast ratio for two opaque #RRGGBB colors. Return AA/AAA pass flags for normal and large text. Does not assess font size, non-text content, transparency, or an entire design.", "visuals", object(map[string]any{"foreground": str(7), "background": str(7)}, "foreground", "background"), json.RawMessage(`{"foreground":"#0f172a","background":"#ffffff"}`)}, colorContrast},
		{Definition{"time_convert", "Convert a whole-second RFC3339 timestamp with explicit offset into an IANA time zone, e.g. America/Chicago or UTC. Include UTC time, local time, weekday, and Unix seconds. Embedded time-zone data handles DST; no ambiguous local-time input.", "planning", object(map[string]any{"timestamp": str(35), "timezone": str(80)}, "timestamp", "timezone"), json.RawMessage(`{"timestamp":"2026-10-07T20:00:00Z","timezone":"America/Chicago"}`)}, timeConvert},
		{Definition{"inspect_url", "Parse an absolute HTTP or HTTPS URL into scheme, hostname, explicit port, decoded path, query values, and fragment. Reject embedded credentials. Does not fetch the URL, resolve DNS, verify safety, or follow redirects.", "developer", object(map[string]any{"url": str(4096)}, "url"), json.RawMessage(`{"url":"https://example.com/search?q=linear+algebra&page=2"}`)}, inspectURL},
		{Definition{"inspect_image", "Read dimensions and format of base64-encoded PNG, JPEG, or GIF data (at most 128 KiB decoded). Accept raw standard base64, not data URLs. Does not decode pixels or verify the complete image, infer image content, or fetch URLs.", "visuals", object(map[string]any{"base64": str(180000)}, "base64"), json.RawMessage(`{"base64":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5ioAAAAASUVORK5CYII="}`)}, inspectImage},
		{Definition{"make_tone", "Create a mono 16 kHz PCM WAV sine-wave tone, frequency 20 to 4000 Hz and duration 0.1 to 2 seconds. Fixed low amplitude, short fades, no microphone or playback. Return base64 audio plus filename and media type for the caller to save/play.", "audio", object(map[string]any{"frequency_hz": map[string]any{"type": "number", "minimum": 20, "maximum": 4000}, "duration_seconds": map[string]any{"type": "number", "minimum": .1, "maximum": 2}}, "frequency_hz", "duration_seconds"), json.RawMessage(`{"frequency_hz":440,"duration_seconds":0.5}`)}, makeTone},
		{Definition{"normalize_csv", "Convert CSV to TSV or TSV to CSV with proper quoting, preserving string cells and row order. Input must have a header, consistent rows, <=1000 data rows, <=32 columns, <=128 KiB, and <=4096 bytes per cell. No numeric coercion, spreadsheet formula execution, or file reads.", "data", object(map[string]any{"text": str(128 * 1024), "from": choice("csv", "tsv"), "to": choice("csv", "tsv")}, "text", "from", "to"), json.RawMessage(`{"text":"name,hours\nC,4\nPython,7","from":"csv","to":"tsv"}`)}, normalizeCSV},
		{Definition{"generate_uuid", "Generate 1 to 100 cryptographically random RFC 9562 version-4 UUIDs. Return canonical lowercase UUID strings; no persistence or account creation. Useful for caller-owned records and file identifiers.", "developer", object(map[string]any{"count": integer(1, 100)}, "count"), json.RawMessage(`{"count":3}`)}, generateUUID},
	}...)
}
