package tools

import "encoding/json"

func integer(min, max int) map[string]any {
	return map[string]any{"type": "integer", "minimum": min, "maximum": max}
}

func init() {
	registry = append(registry, []entry{
		{Definition{"solve_quadratic", "Solve a*x^2+b*x+c=0, including linear/constant degeneracies and complex roots. Approximate float64 results with a stable real-root formula; discriminant sign is exact for the supplied float64 coefficients.", "math", object(map[string]any{"a": number(), "b": number(), "c": number()}, "a", "b", "c"), json.RawMessage(`{"a":1,"b":-5,"c":6}`)}, solveQuadratic},
		{Definition{"linear_regression", "Fit y=intercept+slope*x to 2 to 4096 supplied [x,y] points using ordinary least squares. Return slope, intercept, correlation, R-squared, and RMSE. Constant x is rejected; constant y has null correlation and R-squared. Association does not establish causation.", "data", object(map[string]any{"points": array(array(number(), 2, 2), 2, 4096)}, "points"), json.RawMessage(`{"points":[[1,3],[2,5],[3,7]]}`)}, linearRegression},
		{Definition{"solve_linear_system", "Exactly row-reduce an integer coefficient matrix and constants using rational arithmetic. Up to 8 equations and 8 variables, integers within +/-1 million. Return rational-string RREF, rank, pivot/free columns (zero-based), consistency, and unique solution when present. No approximation.", "math", object(map[string]any{"matrix": array(array(integer(-1000000, 1000000), 1, 8), 1, 8), "constants": array(integer(-1000000, 1000000), 1, 8)}, "matrix", "constants"), json.RawMessage(`{"matrix":[[1,1],[2,-1]],"constants":[5,1]}`)}, solveLinearSystem},
		{Definition{"combinatorics", "Compute exact factorials, combinations, or permutations for integers 0 <= n <= 1000. Combinations/permutations require 0 <= k <= n. Return a decimal string to preserve large integer precision.", "math", object(map[string]any{"operation": choice("factorial", "combinations", "permutations"), "n": integer(0, 1000), "k": integer(0, 1000)}, "operation", "n"), json.RawMessage(`{"operation":"combinations","n":10,"k":3}`)}, combinatorics},
		{Definition{"number_theory", "Find gcd or lcm for nonnegative integers a and b up to 1 billion, or prime-factorize a (a >= 2; omit b). gcd(0,0)=0; lcm with zero is 0. Exact decimal strings preserve precision.", "math", object(map[string]any{"operation": choice("gcd", "lcm", "factorize"), "a": integer(0, 1000000000), "b": integer(0, 1000000000)}, "operation", "a"), json.RawMessage(`{"operation":"factorize","a":360}`)}, numberTheory},
		{Definition{"convert_base", "Convert an integer string between bases 2, 8, 10, and 16. Accept optional leading minus, no prefixes or separators, at most 256 characters. Exact arithmetic; output uses lowercase digits.", "developer", object(map[string]any{"value": str(256), "from": choice("2", "8", "10", "16"), "to": choice("2", "8", "10", "16")}, "value", "from", "to"), json.RawMessage(`{"value":"ff","from":"16","to":"10"}`)}, convertBase},
		{Definition{"inspect_json", "Parse a JSON string up to 64 KiB with at most 32 nesting levels. Reject duplicate object keys and trailing content. Return valid=true, root type, and formatted JSON. Preserve number spelling and precision; no code execution.", "developer", object(map[string]any{"json": str(64 * 1024)}, "json"), json.RawMessage(`{"json":"{\"name\":\"Edsger\",\"tools\":22}"}`)}, inspectJSON},
		{Definition{"test_regex", "Find up to 50 regex matches and captured groups in text. Uses Go RE2 syntax with linear-time matching; no lookaround or backreferences. Byte offsets are zero-based and end-exclusive. Case flags can be embedded, e.g. (?i). No replacement or execution.", "developer", object(map[string]any{"pattern": str(512), "text": str(64 * 1024)}, "pattern", "text"), json.RawMessage(`{"pattern":"[0-9]+","text":"Scores: 85, 90, 95"}`)}, testRegex},
		{Definition{"encode_text", "Encode/decode text as standard padded base64, hexadecimal, or URL query text. Decoded bytes must be valid UTF-8 without nulls and at most 64 KiB. Query encoding maps spaces to +. Encoding is not encryption.", "developer", object(map[string]any{"operation": choice("encode", "decode"), "format": choice("base64", "hex", "url_query"), "text": str(64 * 1024)}, "operation", "format", "text"), json.RawMessage(`{"operation":"encode","format":"base64","text":"Hello Edsger"}`)}, encodeText},
		{Definition{"hash_text", "Compute SHA-256 or SHA-512 of the exact UTF-8 text bytes, including whitespace. Return lowercase hexadecimal. For checksums and content comparison; not password hashing or encryption.", "developer", object(map[string]any{"algorithm": choice("sha256", "sha512"), "text": str(64 * 1024)}, "algorithm", "text"), json.RawMessage(`{"algorithm":"sha256","text":"hello"}`)}, hashText},
		{Definition{"compare_text", "Compare two texts line by line. Return a bounded diff using longest common subsequence, counts of inserted/deleted lines, and equal/insert/delete operations. Maximum 200 lines per text. CRLF and CR normalize to LF; other whitespace is significant.", "writing", object(map[string]any{"before": str(16 * 1024), "after": str(16 * 1024)}, "before", "after"), json.RawMessage(`{"before":"Learn\nBuild","after":"Learn\nCreate\nBuild"}`)}, compareText},
		{Definition{"transform_text", "Apply one deterministic text transformation: lowercase, uppercase, trim, normalize whitespace, or sort/deduplicate nonempty lines. Unicode-aware casing, no translation or rewriting. Line operations normalize CRLF/CR to LF.", "writing", object(map[string]any{"operation": choice("lowercase", "uppercase", "trim", "normalize_whitespace", "sort_lines", "unique_lines"), "text": str(64 * 1024)}, "operation", "text"), json.RawMessage(`{"operation":"unique_lines","text":"C\nPython\nC\nLua"}`)}, transformText},
		{Definition{"make_flashcards", "Package 1 to 100 supplied question/answer pairs as CSV flashcards and Markdown study notes. Uses the supplied facts; does not generate or verify answers. Returns both files as text; does not save data.", "study", object(map[string]any{"title": str(120), "cards": array(object(map[string]any{"question": str(1000), "answer": str(2000)}, "question", "answer"), 1, 100)}, "title", "cards"), json.RawMessage(`{"title":"Linear algebra","cards":[{"question":"When is a map onto?","answer":"When its matrix has a pivot in every row."}]}`)}, makeFlashcards},
		{Definition{"grade_quiz", "Compare 1 to 100 supplied answer/key strings, trimming and collapsing whitespace and ignoring Unicode case. No semantic grading or partial credit. Return per-answer results and percentage; user supplies the correct answer key.", "study", object(map[string]any{"answers": array(str(2000), 1, 100), "key": array(str(2000), 1, 100)}, "answers", "key"), json.RawMessage(`{"answers":["Elasticity","authorization"],"key":["elasticity","authentication"]}`)}, gradeQuiz},
		{Definition{"make_calendar_event", "Create a single downloadable ICS event from title, start/end RFC3339 timestamps with explicit offsets, and optional description/location. Return calendar text; does not schedule or send invitations. End must be after start; output times use UTC.", "planning", object(map[string]any{"title": str(120), "start": str(35), "end": str(35), "description": str(4000), "location": str(300)}, "title", "start", "end"), json.RawMessage(`{"title":"Study session","start":"2026-10-07T18:00:00-05:00","end":"2026-10-07T19:00:00-05:00"}`)}, makeCalendarEvent},
	}...)
}
