package tools

import "encoding/json"

func init() {
	registry = append(registry, entry{Definition{"make_worksheet", "Build a printable written-practice worksheet and a separate worked answer key from 1 to 30 supplied exercises. Returns two offline HTML files without scripts or network requests. Text is escaped; content is supplied, not fact-checked. No model, PDF compiler, or arbitrary code is run.", "study", object(map[string]any{
		"title": str(120), "instructions": str(500), "exercises": array(object(map[string]any{"prompt": str(1000), "answer": str(1000), "explanation": str(2000)}, "prompt", "answer", "explanation"), 1, 30),
	}, "title", "instructions", "exercises"), json.RawMessage(`{"title":"Algebra practice","instructions":"Show your working.","exercises":[{"prompt":"Solve 2x + 3 = 11.","answer":"x = 4","explanation":"Subtract 3, then divide by 2."}]}`)}, makeWorksheet})
	registry = append(registry, []entry{
		{Definition{"make_study_app", "Create a self-contained offline HTML quiz with answer explanations, retry-missed practice, local progress, and progress export. Supply 1 to 100 multiple-choice questions with exactly one zero-based correct_index. Content is supplied, not fact-checked. Return HTML for the caller to save/open in a script-enabled isolated preview; no hosting or account needed.", "study", object(map[string]any{
			"title": str(120), "questions": array(object(map[string]any{"prompt": str(1000), "choices": array(str(500), 2, 6), "correct_index": integer(0, 5), "explanation": str(2000)}, "prompt", "choices", "correct_index", "explanation"), 1, 100),
		}, "title", "questions"), json.RawMessage(`{"title":"Linear algebra practice","questions":[{"prompt":"A matrix with a pivot in every column is…","choices":["One-to-one","Always onto"],"correct_index":0,"explanation":"A pivot in every column means there are no free variables in the homogeneous system."}]}`)}, makeStudyApp},
		{Definition{"make_data_dashboard", "Create an offline interactive HTML chart/table dashboard with series toggles, line/bar views, selected-series summaries, and CSV export. Supply 1 to 200 unique category labels and 1 to 6 named numeric series of equal length. Categories retain supplied order; no inferred dates, causation, units, or statistics beyond count/sum/mean/min/max. Return HTML; caller saves/opens it in an isolated script-enabled preview.", "data", object(map[string]any{
			"title": str(120), "labels": array(str(80), 1, 200), "series": array(object(map[string]any{"name": str(80), "values": array(number(), 1, 200)}, "name", "values"), 1, 6),
		}, "title", "labels", "series"), json.RawMessage(`{"title":"Study hours","labels":["Monday","Tuesday","Wednesday"],"series":[{"name":"Math","values":[2,3,1]},{"name":"Programming","values":[1,2,4]}]}`)}, makeDataDashboard},
		{Definition{"make_sorting_lab", "Create an offline HTML sorting visualizer with play/pause, single-step, reset, speed control, comparison/write counts, and a server-computed trace. Algorithms: bubble, insertion, selection. Supply 2 to 32 finite numbers. Ascending sort, no code execution. Return sorted values, counters, frame_count, and HTML containing the bounded snapshots for isolated script-enabled preview.", "study", object(map[string]any{"algorithm": choice("bubble", "insertion", "selection"), "values": array(number(), 2, 32)}, "algorithm", "values"), json.RawMessage(`{"algorithm":"insertion","values":[5,2,4,1,3]}`)}, makeSortingLab},
		{Definition{"make_pixel_art", "Export a 1 to 64 square-grid-size sprite as real PNG and SVG using supplied palette indices. Rows may be rectangular, but must have equal widths. Palette: 1 to 16 #RRGGBB or #RRGGBBAA colors; alpha supports transparency. Pixel scale 1 to 16. Returns base64 PNG and SVG; no AI image generation, editor, or external renderer.", "visuals", object(map[string]any{
			"palette": array(str(9), 1, 16), "pixels": array(array(integer(0, 15), 1, 64), 1, 64), "scale": integer(1, 16),
		}, "palette", "pixels", "scale"), json.RawMessage(`{"palette":["#00000000","#2563EB","#FFFFFF"],"pixels":[[0,1,0],[1,2,1],[0,1,0]],"scale":16}`)}, makePixelArt},
		{Definition{"make_music_sequence", "Create a mono 16 kHz PCM WAV melody from 1 to 64 supplied notes/rests at 30 to 240 BPM. Notes: MIDI numbers 48 to 96 or rest; each lasts 0.25 to 4 beats. Sine timbre, fixed low amplitude, per-note fades; total at most 16 seconds. Return WAV base64 and pitch/timing metadata. No microphone, playback, generative composition, or copyrighted library.", "audio", object(map[string]any{
			"bpm": map[string]any{"type": "number", "minimum": 30, "maximum": 240}, "notes": array(object(map[string]any{"pitch": str(4), "beats": map[string]any{"type": "number", "minimum": .25, "maximum": 4}}, "pitch", "beats"), 1, 64),
		}, "bpm", "notes"), json.RawMessage(`{"bpm":120,"notes":[{"pitch":"60","beats":1},{"pitch":"64","beats":1},{"pitch":"67","beats":2},{"pitch":"rest","beats":1}]}`)}, makeMusicSequence},
		{Definition{"plan_project", "Compute an exact integer-minute dependency schedule, critical tasks, slack, total work, and minimum elapsed duration assuming unlimited parallel workers for 1 to 60 tasks. Supply unique IDs, positive duration_minutes, and depends_on IDs. Dependencies must form a DAG. Assumes unlimited parallel workers, elapsed minutes, no calendars/resources. Return schedule and CSV; does not execute tasks or create reminders.", "planning", object(map[string]any{
			"tasks": array(object(map[string]any{"id": str(40), "title": str(120), "duration_minutes": integer(1, 100000), "depends_on": array(str(40), 0, 59)}, "id", "title", "duration_minutes", "depends_on"), 1, 60),
		}, "tasks"), json.RawMessage(`{"tasks":[{"id":"design","title":"Design","duration_minutes":30,"depends_on":[]},{"id":"build","title":"Build","duration_minutes":60,"depends_on":["design"]},{"id":"docs","title":"Write docs","duration_minutes":20,"depends_on":["design"]},{"id":"test","title":"Test","duration_minutes":15,"depends_on":["build","docs"]}]}`)}, planProject},
	}...)
}
